resources:
  repositories:
    - repository: devops
      type: github
      name: MobisysGmbh/devops-templates
      endpoint: MobisysGmbH
      ref: refs/heads/release/v7

trigger: none
pr: none

extends:
  template: /yaml/kickstarter-templates/package-pipeline.yml@devops
  parameters:
    vmImage: ubuntu-latest
    requireNvmrc: true
    allowedPublishingBranches: refs/heads/master
    packageType: npm
    artifactsDirectoryToPublish: $(Build.SourcesDirectory)
