resources:
  repositories:
    - repository: devops
      type: github
      name: MobisysGmbh/devops-templates
      endpoint: MobisysGmbH
      ref: refs/heads/release/v8

trigger: none
pr: none

extends:
  template: /yaml/kickstarter-templates/package-pipeline.yml@devops
  parameters:
    vmImage: ubuntu-latest
    requireNvmrc: true
    allowedPublishingBranches: refs/heads/master
    packageType: npm
    prePublishSteps:
      - task: CopyFiles@2
        inputs:
          Contents: 'mobisys-internal-cordova-plugin-device-*.tgz'
          TargetFolder: 'publish'
          CleanTargetFolder: true
    artifactsDirectoryToPublish: $(Build.SourcesDirectory)/publish
